#pragma once

#define KNOTH_MOUSE_BUTTON_1         0
#define KNOTH_MOUSE_BUTTON_2         1
#define KNOTH_MOUSE_BUTTON_3         2
#define KNOTH_MOUSE_BUTTON_4         3
#define KNOTH_MOUSE_BUTTON_5         4
#define KNOTH_MOUSE_BUTTON_6         5
#define KNOTH_MOUSE_BUTTON_7         6
#define KNOTH_MOUSE_BUTTON_8         7
#define KNOTH_MOUSE_BUTTON_LAST      KNOTH_MOUSE_BUTTON_8
#define KNOTH_MOUSE_BUTTON_LEFT      KNOTH_MOUSE_BUTTON_1
#define KNOTH_MOUSE_BUTTON_RIGHT     KNOTH_MOUSE_BUTTON_2
#define KNOTH_MOUSE_BUTTON_MIDDLE    KNOTH_MOUSE_BUTTON_3